In [1]:
# Cell 1 — imports
import sys
from src.pipeline import *

In [2]:
# Cell 2 — pull and engineer features (fit=True for training season)
raw = pull_statcast(season=2023)
df, scaler, le = build_features(raw, season=2023, fit=True)

  Pulling 2023-04-01 -> 2023-04-30...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:02<00:00, 12.53it/s]

  Pulling 2023-05-01 -> 2023-05-31...
This is a large query, it may take a moment to complete

100%|██████████| 31/31 [00:01<00:00, 17.97it/s]

  Pulling 2023-06-01 -> 2023-06-30...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:01<00:00, 19.54it/s]

  Pulling 2023-07-01 -> 2023-07-31...
This is a large query, it may take a moment to complete

100%|██████████| 31/31 [00:01<00:00, 18.24it/s]
/opt/miniconda3/envs/dugout/lib/python3.12/site-packages/pybaseball/statcast.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_data = pd.concat(dataframe_list, axis=0).convert_dtypes(convert_string=False)

  Pulling 2023-08-01 -> 2023-08-31...
This is a large query, it may take a moment to complete

100%|██████████| 31/31 [00:02<00:00, 15.20it/s]

  Pulling 2023-09-01 -> 2023-09-30...
This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:02<00:00, 13.07it/s]

  Building features...
  Dropped 7,156 rows with missing physics (1.0%)
  Scaler fitted.

In [3]:
# Cell 3 — Stage 1: train
model = train_model(df, scaler, le)
df = score_pitches(df, model, scaler)
save_artifacts(model, scaler, le)
save_cache(df, season=2023)

[Stage 1] Training PitchValueNet...
  Train: 460,825 | Test: 242,320
  Epoch 01: train=0.05221  val=0.05261
  Epoch 02: train=0.05137  val=0.05240
  Epoch 03: train=0.05123  val=0.05228
  Epoch 04: train=0.05114  val=0.05222
  Epoch 05: train=0.05108  val=0.05218
  Epoch 06: train=0.05105  val=0.05217
  Epoch 07: train=0.05102  val=0.05213
  Epoch 08: train=0.05099  val=0.05213
  Epoch 09: train=0.05097  val=0.05212
  Epoch 10: train=0.05095  val=0.05210
  Artifacts saved to artifacts/
  Cache saved to data/cache_2023.parquet

In [4]:
# Cell 4 — Stage 2: leaderboard
stage2 = build_leaderboard(df, as_of_date='2023-09-30')
stage2.head(10)

Empty DataFrame
Columns: [pitcher, pitch_count, weighted_xrv]
Index: []

In [5]:
# Cell 5 — Stage 3: Empirical Bayes
stage3 = compute_empirical_bayes(df, as_of_date='2023-09-30')
stage3.head(10)

Empty DataFrame
Columns: []
Index: []

In [6]:
# Cell 6 — Validation
validate(stage2, season=2023)

[Validation] Spearman vs FanGraphs...
  Stuff+: r=nan  p=nan  n=0
  SIERA: r=nan  p=nan  n=0

   Metric  Spearman r  p-value  n
0  Stuff+         NaN      NaN  0
1   SIERA         NaN      NaN  0

In [7]:
# Cell 7 — Trajectory for a specific pitcher
import pandas as pd
dates = pd.date_range(start='2023-04-01', end='2023-09-30', freq='W')
traj = pitcher_trajectory(df, pitcher_id=<MLBAM_ID>, dates=dates)
traj.plot(x='date', y='smoothed_xrv')

SyntaxError: invalid syntax (4111212314.py, line 4)